
name: 铁巴

on:
  workflow_dispatch:
  schedule:
     - cron: '5 18 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        TB_COOKIE: ${{ secrets.TB_COOKIE }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.TB_COOKIE
        run: |
          npm install
      - name: '运行 【铁巴】'
        if: env.WB_TOKEN
        run: |
          node Task/TB.js
        env:
          TB_COOKIE: ${{ secrets.TB_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}qkd/master/Task/TB.js
          
